osx_image: xcode8.3
os:
  - linux
  - osx

dist: trusty
sudo: false

language: node_js
node_js: "8"
compiler: clang

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

install:
  - yarn

script:
  - yarn lint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn build:linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn build:mac && yarn build:win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: releases
  api_key:
    secure: WguojeKSRQ14sz+3bPvBX767vHIOUn8TRVgRRRfVs1eUtmAUpOwsNE9xs39xtYNtrlcqOUXX68hIoJ7sWNhuSRNDkDOFt1adzv3Ivtri0+8bxtbTEQh5lDY0SvQYYhHPW9BICKXeNrH0usRrlZoT1+yA7sCkHXsggWAJchYQLxe6koF0uxkepROYciJKUiNj28RUWKeKthJAear8gdCfXq40wIa4OfDBTvqRGxmdcyK+3eTOunfmblFCspfXPadlonberOmZcC1Vn4ul/WOZXRI3cO5+MzgMjG6Exx0fnWDRaplNV+6ADhH5EcT4rzdvM2BYeEdJJ343qKl/eUruH6MqujY6puESqoNxTWq6YEx4SMUCmwId7mGuasNTbRY7yCQkQaDddPdhFtpd4J0cZklsKabE12Gbw3hyYpiMMZLErx+0IG2IjQfc2x4nLd9zL5xgo2kvEWkraSJcA/8GrWdoZoSCBo1Dfm7yzXRhlLzQVUwvKgxDsP1kKbeKnHJp33Rj8qaSGFVM4HN9buf6EeiTmXefDiPaCG0DaDcnnUM14JmvO1cKSdUie9mu0YwsH+AJ/kZLV/kpJ7TDjEg6EnH1eUkM5tdTlM2r6kRi630yKsRHEZkwAZ+F8Zb7IfNrYQTIfGocNm+QR1+0tzlKXN3DZ4P4F3LMPIq+cea6mSo=
  skip_cleanup: true
  file_glob: true
  file: ./dist/foxlet*
  on:
    tags: true

after_deploy:
  - echo "SHA1 Information"
  - sha1sum foxlet-*
  - echo "MD5 Information"
  - md5sum foxlet-*

notifications:
  email: false
